# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\下拉框控件.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 2, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setObjectName("comboBox")
        # self.comboBox.addItem("")
        # self.comboBox.addItem("")
        # self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.comboBox.activated.connect(self.choicetext)  # 变更时调用函数
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "选择框"))

        text_comboBox_list = ['巴楚县人民医院', '惠州市人民医院', '广州医科大学附属第一医院', '重庆市第五人民医院']  # 可通过配置或数据库连接实现
        for i, t in enumerate(text_comboBox_list):
            # print(i,t)
            self.comboBox.addItem("")
            self.comboBox.setItemText(i, _translate("Form", t))
        # self.comboBox.setItemText(0, _translate("Form", "巴楚县人民医院"))
        # self.comboBox.setItemText(1, _translate("Form", "惠州市人民医院"))
        # self.comboBox.setItemText(2, _translate("Form", "广州医科大学附属第一医院"))

    def choicetext(self):
        '''将选择文本输出到textBrowser显示框中'''
        import time
        self.textBrowser.append('{} 选框变更为{}'.format(time.strftime('%Y-%m-%d %H:%M:%S'), self.comboBox.currentText()))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())